### ISSUE TITLE
NoSuchTableException: q05 Step 2/3: logistic regression failure

### ISSUE THREAD

**Issue by nakhanha** [dharmeshkakadia/tpcxbb-hive2#1]
spark-submit --class io.bigdatabenchmark.v1.queries.q05.LogisticRegression /home/nakhanha/Big-Data-Benchmark-for-Big-Bench/engines/hive/queries/Resources/bigbench-ml-spark.jar --fromHiveMetastore true -i bigbench.q05_hive_engine_validation_power_test_0_temp -o /user/nakhanha/benchmarks/bigbench/queryResults/q05_hive_engine_validation_power_test_0_result// --type LBFGS --step-size 1 --iterations 20 --lambda 0 --numClasses 2 --convergenceTol 1e-5 --numCorrections 10 --saveClassificationResult false --saveMetaInfo true --verbose false

SPARK_MAJOR_VERSION is set to 1, using Spark
Run LogisticRegression with options: Map('csvInputDelimiter -> ,, 'fromHiveMetastore -> true, 'verbose -> false, 'saveMetaInfo -> true, 'lambda -> 0, 'numCorrections -> 10, 'stepsize -> 1, 'convergenceTol -> 1e-5, 'iter -> 20, 'output -> /user/nakhanha/benchmarks/bigbench/queryResults/q05_hive_engine_validation_power_test_0_result//, 'type -> LBFGS, 'saveClassificationResult -> false, 'input -> bigbench.q05_hive_engine_validation_power_test_0_temp, 'numClasses -> 2)
18/06/06 22:34:47 INFO slf4j.Slf4jLogger: Slf4jLogger started
18/06/06 22:34:47 INFO Remoting: Starting remoting
18/06/06 22:34:47 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@10.0.0.21:29865]
loading data from metastore table: "bigbench.q05_hive_engine_validation_power_test_0_temp" ...
18/06/06 22:34:49 INFO DataNucleus.Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
18/06/06 22:34:49 INFO DataNucleus.Persistence: Property datanucleus.cache.level2 unknown - will be ignored
18/06/06 22:34:49 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/06 22:34:49 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/06 22:34:56 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:34:56 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:02 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:02 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:04 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:06 INFO DataNucleus.Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
18/06/06 22:35:06 INFO DataNucleus.Persistence: Property datanucleus.cache.level2 unknown - will be ignored
18/06/06 22:35:06 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/06 22:35:06 WARN DataNucleus.Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
18/06/06 22:35:08 INFO DataNucleus.Query: Reading in results for query "org.datanucleus.store.rdbms.query.SQLQuery@0" since the connection used is closing
18/06/06 22:35:08 INFO DataNucleus.Datastore: The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
Exception in thread "main" org.apache.spark.sql.catalyst.analysis.NoSuchTableException
at org.apache.spark.sql.hive.client.ClientInterface$$anonfun$getTable$1.apply(ClientInterface.scala:122)
at org.apache.spark.sql.hive.client.ClientInterface$$anonfun$getTable$1.apply(ClientInterface.scala:122)
at scala.Option.getOrElse(Option.scala:120)
at org.apache.spark.sql.hive.client.ClientInterface$class.getTable(ClientInterface.scala:122)
at org.apache.spark.sql.hive.client.ClientWrapper.getTable(ClientWrapper.scala:61)
at org.apache.spark.sql.hive.HiveMetastoreCatalog.lookupRelation(HiveMetastoreCatalog.scala:414)
at org.apache.spark.sql.hive.HiveContext$$anon$2.org$apache$spark$sql$catalyst$analysis$OverrideCatalog$$super$lookupRelation(HiveContext.scala:475)
at org.apache.spark.sql.catalyst.analysis.OverrideCatalog$class.lookupRelation(Catalog.scala:162)
at org.apache.spark.sql.hive.HiveContext$$anon$2.lookupRelation(HiveContext.scala:475)
at org.apache.spark.sql.SQLContext.table(SQLContext.scala:831)
at org.apache.spark.sql.SQLContext.table(SQLContext.scala:827)
at io.bigdatabenchmark.v1.queries.q05.LogisticRegression$.loadfromHiveMetastore(LogisticRegression.scala:188)
at io.bigdatabenchmark.v1.queries.q05.LogisticRegression$.main(LogisticRegression.scala:99)
at io.bigdatabenchmark.v1.queries.q05.LogisticRegression.main(LogisticRegression.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:750)
at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/06/06 22:35:09 INFO remote.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
18/06/06 22:35:09 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
18/06/06 22:35:09 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
nakhanha@hn0-hdil4:~/Big-Data-Benchmark-for-Big-Bench/bin$

**Is there something I am missing. because I checked in hive cli for tables and table exist. Please let me know.**

hive> use bigbench;
OK
Time taken: 0.054 seconds
hive> show tables;
OK
customer
customer_address
customer_demographics
date_dim
household_demographics
income_band
inventory
item
item_marketprices
product_reviews
promotion
q01_hive_engine_validation_power_test_0_result
q02_hive_engine_validation_power_test_0_result
q03_hive_engine_validation_power_test_0_result
q04_hive_engine_validation_power_test_0_result
**q05_hive_engine_validation_power_test_0_temp**
reason
ship_mode
store
store_returns
store_sales
time_dim
warehouse
web_clickstreams
web_page
web_returns
web_sales
web_site
Time taken: 0.123 seconds, Fetched: 28 row(s)
hive>

**Comment by dharmeshkakadia** [comment]
I am not sure I understand whats the ask here.

**Comment by nakhanha** [comment]
fixed the issue with by connecting hive meta-store with spark

https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.4/bk_spark-component-guide/content/spark-config-hive.html
